/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room.glb 
*/

import React, { useState, useEffect } from 'react'
import * as THREE from 'three'
import { useGLTF, useTexture, useCursor, Edges } from '@react-three/drei'

// Added 'isMobile' to props
function Monitor({ geometry, texture, isHighlighted, isSitting, transitionDone, isMobile, edgeOffset = [0, 0, 0], ...props }) {
  const [hovered, setHovered] = useState(false)
  
  // only allow monitor interaction if sitting and transition is done
  const canInteract = isSitting && transitionDone

  // cursor only shows if we are allowed to interact
  useCursor(hovered && canInteract) 

  const showBright = canInteract && (hovered || isHighlighted);

  return (
    <mesh
      geometry={geometry}
      {...props}
      onPointerOver={(e) => {
        if (!isMobile && canInteract) {
          e.stopPropagation()
          setHovered(true)
        }
      }}
      onPointerOut={() => setHovered(false)}
    >
      <meshBasicMaterial
        map={texture}
        toneMapped={false}
        color={showBright ? "white" : "#747474"} 
      />

      {showBright && (
        <Edges 
          scale={1}
          threshold={15}
          lineWidth={2} 
          color="#434343" 
          renderOrder={1000}
          position={edgeOffset} 
        />
      )}

    </mesh>
  )
}

export function Model({isSitting, ...props}) {

  // load model
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/Room.glb')

  // load about screen
  const aboutScreenTexture = useTexture(import.meta.env.BASE_URL + 'images/AboutPageScreenshot.png')
  aboutScreenTexture.flipY = false 
  aboutScreenTexture.toneMapped = false 
  aboutScreenTexture.anisotropy = 16 
  aboutScreenTexture.minFilter = THREE.LinearFilter
  aboutScreenTexture.magFilter = THREE.LinearFilter

  // load projects screen
  const projectsScreenTexture = useTexture(import.meta.env.BASE_URL + 'images/ProjectsPageScreenshot.png')
  projectsScreenTexture.flipY = false 
  projectsScreenTexture.toneMapped = false 
  projectsScreenTexture.anisotropy = 16 
  projectsScreenTexture.minFilter = THREE.LinearFilter
  projectsScreenTexture.magFilter = THREE.LinearFilter

  // load contact screen
  const contactScreenTexture = useTexture(import.meta.env.BASE_URL + 'images/ContactPageScreenshot.png')
  contactScreenTexture.flipY = false 
  contactScreenTexture.toneMapped = false 
  contactScreenTexture.anisotropy = 16 
  contactScreenTexture.minFilter = THREE.LinearFilter
  contactScreenTexture.magFilter = THREE.LinearFilter

  // mobile screen highlight cycling
  const [highlightedIndex, setHighlightedIndex] = useState(null)
  const [transitionDone, setTransitionDone] = useState(false)
  const [isMobile, setIsMobile] = useState(false)

  // mobile detection listener
  useEffect(() => {
    // check for touch capability
    const mediaQuery = window.matchMedia('(pointer: coarse)')
    setIsMobile(mediaQuery.matches)

    const handleChange = (e) => setIsMobile(e.matches)
    mediaQuery.addEventListener('change', handleChange)
    return () => mediaQuery.removeEventListener('change', handleChange)
  }, [])

  // wait for camera to land before allowing interaction
  useEffect(() => {
    if (isSitting) {
      const timer = setTimeout(() => setTransitionDone(true), 1500)
      return () => clearTimeout(timer)
    } else {
      setTransitionDone(false)
    }
  }, [isSitting])

  // mobile monitor cycling
  useEffect(() => {
    if (isMobile) {
      const interval = setInterval(() => {
        setHighlightedIndex((prev) => (prev === null ? 0 : (prev + 1) % 3)) 
      }, 2000)
      return () => clearInterval(interval)
    } else {
      setHighlightedIndex(null)
    }
  }, [isMobile])

  return (
    <group {...props} dispose={null}>
      <group position={[0.209, 0, 0.882]}>
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube014.geometry} material={materials['Mouse - Shiny Grey']} />
          <mesh geometry={nodes.Cube014_1.geometry} material={materials['Mouse - Mat Grey']} />
        </group>
        <mesh geometry={nodes.Chair.geometry} material={materials.Leather} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector001.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector002.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.DeskTop} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Legs} />
        </group>
        <group scale={[1.875, 1.082, 1.875]}>
          <mesh geometry={nodes.Plane_1.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials.Walls} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials.Wood} />
        </group>
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube004_2.geometry} material={materials.Keys_Lettered} />
          <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube004_4.geometry} material={materials.Key_Plastic} />
        </group>
        <mesh geometry={nodes.MonitorLeft.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />
        
        {/* left monitor */}
        <Monitor 
          geometry={nodes.MonitorLeftScreen.geometry}
          position={[-0.22, 0, -0.874]}
          texture={aboutScreenTexture}
          isHighlighted={isMobile && highlightedIndex === 0}
          isSitting={isSitting} 
          transitionDone={transitionDone}
          isMobile={isMobile}
          edgeOffset={[0.01, 0, -0.005]}
        />

        <mesh geometry={nodes.MonitorMiddle.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />

        {/* middle monitor */}
        <Monitor 
          geometry={nodes.MonitorMiddleScreen.geometry}
          position={[-0.22, 0, -0.874]}
          texture={projectsScreenTexture}
          isHighlighted={isMobile && highlightedIndex === 1}
          isSitting={isSitting}
          transitionDone={transitionDone}
          isMobile={isMobile}
          edgeOffset={[0.01, 0, 0]}
        />

        <mesh geometry={nodes.MonitorRight.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />
        
        {/* right monitor */}
        <Monitor 
          geometry={nodes.MonitorRightScreen.geometry}
          position={[-0.22, 0, -0.874]}
          texture={contactScreenTexture}
          isHighlighted={isMobile && highlightedIndex === 2}
          isSitting={isSitting}
          transitionDone={transitionDone} 
          isMobile={isMobile}
          edgeOffset={[0.01, 0, 0.005]} 
        />

        <mesh geometry={nodes.Mousepad.geometry} material={materials['Material.001']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Plane.geometry} material={materials.Floor} scale={[1.875, 1, 1.875]} />
        <mesh geometry={nodes.Plane002.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Top.geometry} material={materials['Mouse - Mat Grey']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Wheel.geometry} material={materials['Mouse - Wheel Grey']} position={[-0.224, 0, -0.874]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Room.glb')
