/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/RoomV3.glb 
*/

import React from 'react'
import * as THREE from 'three'
import { useGLTF, useTexture } from '@react-three/drei'

export function Model(props) {

  // load model
  const { nodes, materials } = useGLTF('/models/RoomV3.glb')

  // load about screen
  const screenTexture = useTexture('/images/AboutPageScreenshot.png')
  screenTexture.flipY = false 
  screenTexture.toneMapped = false 
  screenTexture.anisotropy = 16 
  screenTexture.minFilter = THREE.LinearFilter
  screenTexture.magFilter = THREE.LinearFilter

  return (
    <group {...props} dispose={null}>
      <group position={[0.209, 0, 0.882]}>
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube014.geometry} material={materials['Mouse - Shiny Grey']} />
          <mesh geometry={nodes.Cube014_1.geometry} material={materials['Mouse - Mat Grey']} />
        </group>
        <mesh geometry={nodes.Chair.geometry} material={materials.Leather} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector001.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Connector002.geometry} material={materials['Material.007']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube003.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder002.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder003.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.Wheel} position={[-0.22, 0, -0.874]} />
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.DeskTop} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Legs} />
        </group>
        <group scale={[1.875, 1.082, 1.875]}>
          <mesh geometry={nodes.Plane_1.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials.Walls} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials.Wood} />
        </group>
        <group position={[-0.22, 0, -0.874]}>
          <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.Cube004_2.geometry} material={materials.Keys_Lettered} />
          <mesh geometry={nodes.Cube004_3.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Cube004_4.geometry} material={materials.Key_Plastic} />
        </group>
        <mesh geometry={nodes.MonitorLeft.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />
        
        {/* left monitor screen for screenshot */}
        <mesh 
          geometry={nodes.MonitorLeftScreen.geometry} 
          position={[-0.22, 0, -0.874]}
        >
          <meshBasicMaterial map={screenTexture} toneMapped={false} />
        </mesh>   

        <mesh geometry={nodes.MonitorMiddle.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.MonitorMiddleScreen.geometry} material={materials.Screen_Placeholder_Middle} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.MonitorRight.geometry} material={materials.Plastic_Frame} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.MonitorRightScreen.geometry} material={materials.Screen_Placeholder_Right} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Mousepad.geometry} material={materials['Material.001']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Plane.geometry} material={materials.Floor} scale={[1.875, 1, 1.875]} />
        <mesh geometry={nodes.Plane002.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.Chrome} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Top.geometry} material={materials['Mouse - Mat Grey']} position={[-0.22, 0, -0.874]} />
        <mesh geometry={nodes.Wheel.geometry} material={materials['Mouse - Wheel Grey']} position={[-0.224, 0, -0.874]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/RoomV3.glb')
