/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Room.glb --transform --out src/Room.jsx 
Files: public/models/Room.glb [26.95MB] > C:\Users\tavia\dev\portfolio\Room-transformed.glb [1.05MB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Chair.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Connector.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Mousepad.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.DeskTop} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Legs} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Walls} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.Wood} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials.Floor} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cube004_1.geometry} material={materials.Keys_Lettered} />
      <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/Room-transformed.glb')
